.TH HELLO  1  1970-01-01  "Hello 0.0.0"  "Hello Manual"

.SH NAME

hello \- print "Hello world!" to standard output

.SH SYNOPSIS

hello

.SH DESCRIPTION

Print "Hello world!" to standard output.

.SH OPTIONS

None.

.SH OPERANDS

None.

.SH STDIN

Not used.

.SH INPUT FILES

None.

.SH ENVIRONMENT VARIABLES

None.

.SH ASYNCHRONOUS EVENTS

Default.

.SH STDOUT

The \fIhello\fR utility shall write "Hello world!" to standard output.

.SH STDERR

Not used.

.SH OUTPUT FILES

None.

.SH EXTENDED DESCRIPTION

None.

.SH EXIT STATUS

Zero.

.SH CONSEQUENCES OF ERRORS

None.
