version: 2
updates:

  - package-ecosystem: "docker"
    directory: "/"
    commit-message:
      prefix: deps(docker)
    labels:
      - deps
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/"
    commit-message:
      prefix: deps(cargo)
    labels:
      - deps
    schedule:
      interval: "weekly"
