[package]
name = "project_name"
version = "0.0.0"
description = "Rust Project Template"
license = "MIT"
publish = false
edition = "2021"
rust-version = "1.56"

[[bin]]
name = "hello"
path = "src/main.rs"

[dependencies]
