name: Build Cargo Crate
description: Build Cargo Crate


inputs:
  sha:
    description: Commit hash
    default: ${{ github.sha }}
  dir:
    description: Directory to checkout repository to
    default: crate


runs:
  using: composite
  steps:
    - uses: ./.github/actions/make-version
      with:
        sha: ${{ inputs.sha }}
        dir: ${{ inputs.dir }}
    - shell: bash
      working-directory: ${{ inputs.dir }}
      run: cargo package
